# Generated by Django 4.2.11 on 2024-04-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tablebooking_time_alter_dish_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablebooking',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
