# Generated by Django 4.2.11 on 2024-04-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_dish_description_alter_dish_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('text', models.TextField(default=None)),
            ],
        ),
    ]
